/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.loader;

public final class R {
    private R() {
    }

    public static final class attr {
        private attr() {
        }

        public static final int alpha = 0x7f030027;
        public static final int font = 0x7f0300d7;
        public static final int fontProviderAuthority = 0x7f0300d9;
        public static final int fontProviderCerts = 0x7f0300da;
        public static final int fontProviderFetchStrategy = 0x7f0300db;
        public static final int fontProviderFetchTimeout = 0x7f0300dc;
        publi