/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.legacy.coreutils;

public final class R {
    private R() {
    }

    public static final class attr {
        private attr() {
        }

        public static final int alpha = 0x7f030027;